// <auto-generated />
using System;
using API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Models.AccessLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Event")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("event");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("timestamp");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK_AccessLog");

                    b.ToTable("AccessLog", (string)null);
                });

            modelBuilder.Entity("API.Models.Autor", b =>
                {
                    b.Property<int>("IdAutor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_autor");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAutor"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("IdAutor")
                        .HasName("PK__Autor__C252147DA63CC2B9");

                    b.ToTable("Autor", (string)null);
                });

            modelBuilder.Entity("API.Models.Editora", b =>
                {
                    b.Property<int>("IdEditora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_editora");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEditora"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("IdEditora")
                        .HasName("PK__Editora__C252147DA63CC2B9");

                    b.ToTable("Editora", (string)null);
                });

            modelBuilder.Entity("API.Models.Genero", b =>
                {
                    b.Property<int>("IdGenero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_genero");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGenero"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("IdGenero")
                        .HasName("PK__Genero__C252147DA63CC2B9");

                    b.ToTable("Genero", (string)null);
                });

            modelBuilder.Entity("API.Models.Livro", b =>
                {
                    b.Property<int>("IdLivro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_livro");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLivro"));

                    b.Property<DateOnly?>("AnoPublicacao")
                        .HasColumnType("date")
                        .HasColumnName("ano_publicacao");

                    b.Property<string>("CapaUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("capa_url");

                    b.Property<int>("Clicks")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("clicks");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("ativo")
                        .HasColumnName("estado");

                    b.Property<string>("ISBN")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("isbn");

                    b.Property<int?>("IdEditora")
                        .HasColumnType("int")
                        .HasColumnName("id_editora");

                    b.Property<string>("Idioma")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("idioma");

                    b.Property<string>("Sinopse")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("sinopse");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("titulo");

                    b.HasKey("IdLivro")
                        .HasName("PK__Livro__C252147DA63CC2B9");

                    b.HasIndex("IdEditora");

                    b.ToTable("Livro", (string)null);
                });

            modelBuilder.Entity("API.Models.Reserva", b =>
                {
                    b.Property<int>("IdReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_reserva");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReserva"));

                    b.Property<bool>("Confirmada")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("DataFim")
                        .HasColumnType("date")
                        .HasColumnName("data_fim");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("date")
                        .HasColumnName("data_inicio");

                    b.Property<int>("IdUtilizador")
                        .HasColumnType("int")
                        .HasColumnName("id_utilizador");

                    b.HasKey("IdReserva")
                        .HasName("PK__Reserva__423CBE5D3753DD0B");

                    b.HasIndex("IdUtilizador");

                    b.ToTable("Reserva", (string)null);
                });

            modelBuilder.Entity("API.Models.Review", b =>
                {
                    b.Property<int>("IdReview")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_review");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReview"));

                    b.Property<DateOnly?>("DataAprovacao")
                        .HasColumnType("date")
                        .HasColumnName("data_aprovacao");

                    b.Property<DateOnly>("DataSubmissao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("data_submissao")
                        .HasDefaultValueSql("(CONVERT([date],getdate()))");

                    b.Property<int>("IdLivro")
                        .HasColumnType("int")
                        .HasColumnName("id_livro");

                    b.Property<int>("IdUtilizador")
                        .HasColumnType("int")
                        .HasColumnName("id_utilizador");

                    b.Property<byte?>("Rating")
                        .HasColumnType("tinyint")
                        .HasColumnName("rating");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("pendente")
                        .HasColumnName("status");

                    b.Property<string>("TextoReview")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("texto_review");

                    b.HasKey("IdReview")
                        .HasName("PK__Review__2F79F8C7613DA0E9");

                    b.HasIndex("IdLivro");

                    b.HasIndex(new[] { "IdUtilizador", "IdLivro" }, "UQ_Review_User_Livro")
                        .IsUnique();

                    b.ToTable("Review", (string)null);
                });

            modelBuilder.Entity("API.Models.Utilizador", b =>
                {
                    b.Property<int>("IdUtilizador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_utilizador");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUtilizador"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("TipoUtilizador")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("tipo_utilizador");

                    b.HasKey("IdUtilizador")
                        .HasName("PK__Utilizad__71C536835F89D131");

                    b.HasIndex(new[] { "Email" }, "UQ__Utilizad__AB6E616464D5E079")
                        .IsUnique();

                    b.ToTable("Utilizador", (string)null);
                });

            modelBuilder.Entity("LivroAutor", b =>
                {
                    b.Property<int>("IdLivro")
                        .HasColumnType("int")
                        .HasColumnName("id_livro");

                    b.Property<int>("IdAutor")
                        .HasColumnType("int")
                        .HasColumnName("id_autor");

                    b.HasKey("IdLivro", "IdAutor");

                    b.HasIndex("IdAutor");

                    b.ToTable("LivroAutor", (string)null);
                });

            modelBuilder.Entity("LivroGenero", b =>
                {
                    b.Property<int>("IdLivro")
                        .HasColumnType("int")
                        .HasColumnName("id_livro");

                    b.Property<int>("IdGenero")
                        .HasColumnType("int")
                        .HasColumnName("id_genero");

                    b.HasKey("IdLivro", "IdGenero");

                    b.HasIndex("IdGenero");

                    b.ToTable("LivroGenero", (string)null);
                });

            modelBuilder.Entity("ReservaLivro", b =>
                {
                    b.Property<int>("IdReserva")
                        .HasColumnType("int")
                        .HasColumnName("id_reserva");

                    b.Property<int>("IdLivro")
                        .HasColumnType("int")
                        .HasColumnName("id_livro");

                    b.HasKey("IdReserva", "IdLivro");

                    b.HasIndex("IdLivro");

                    b.ToTable("ReservaLivro", (string)null);
                });

            modelBuilder.Entity("API.Models.Livro", b =>
                {
                    b.HasOne("API.Models.Editora", "EditoraNavigation")
                        .WithMany("Livros")
                        .HasForeignKey("IdEditora")
                        .HasConstraintName("FK_Livro_Editora");

                    b.Navigation("EditoraNavigation");
                });

            modelBuilder.Entity("API.Models.Reserva", b =>
                {
                    b.HasOne("API.Models.Utilizador", "IdUtilizadorNavigation")
                        .WithMany("Reservas")
                        .HasForeignKey("IdUtilizador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Reserva_Utilizador");

                    b.Navigation("IdUtilizadorNavigation");
                });

            modelBuilder.Entity("API.Models.Review", b =>
                {
                    b.HasOne("API.Models.Livro", "IdLivroNavigation")
                        .WithMany("Reviews")
                        .HasForeignKey("IdLivro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Review_Livro");

                    b.HasOne("API.Models.Utilizador", "IdUtilizadorNavigation")
                        .WithMany("Reviews")
                        .HasForeignKey("IdUtilizador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Review_Utilizador");

                    b.Navigation("IdLivroNavigation");

                    b.Navigation("IdUtilizadorNavigation");
                });

            modelBuilder.Entity("LivroAutor", b =>
                {
                    b.HasOne("API.Models.Autor", null)
                        .WithMany()
                        .HasForeignKey("IdAutor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LivroAutor_Autor");

                    b.HasOne("API.Models.Livro", null)
                        .WithMany()
                        .HasForeignKey("IdLivro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LivroAutor_Livro");
                });

            modelBuilder.Entity("LivroGenero", b =>
                {
                    b.HasOne("API.Models.Genero", null)
                        .WithMany()
                        .HasForeignKey("IdGenero")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LivroGenero_Genero");

                    b.HasOne("API.Models.Livro", null)
                        .WithMany()
                        .HasForeignKey("IdLivro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LivroGenero_Livro");
                });

            modelBuilder.Entity("ReservaLivro", b =>
                {
                    b.HasOne("API.Models.Livro", null)
                        .WithMany()
                        .HasForeignKey("IdLivro")
                        .IsRequired()
                        .HasConstraintName("FK_ReservaLivro_Livro");

                    b.HasOne("API.Models.Reserva", null)
                        .WithMany()
                        .HasForeignKey("IdReserva")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ReservaLivro_Reserva");
                });

            modelBuilder.Entity("API.Models.Editora", b =>
                {
                    b.Navigation("Livros");
                });

            modelBuilder.Entity("API.Models.Livro", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("API.Models.Utilizador", b =>
                {
                    b.Navigation("Reservas");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
